name: Build, Push to AWS ECR & Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag & Push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: my-app
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "=== Testing SSH Connection ==="
            whoami
            pwd
            echo "=== Docker Commands ==="
            aws ecr get-login-password --region eu-north-1 | sudo docker login --username AWS --password-stdin 331355389718.dkr.ecr.eu-north-1.amazonaws.com
            sudo docker stop my-app || true
            sudo docker rm my-app || true
            sudo docker pull 331355389718.dkr.ecr.eu-north-1.amazonaws.com/my-app:latest
            sudo docker run -d --name my-app -p 5000:5000 \
              -e FASTFOREX_API_KEY=${{ secrets.FASTFOREX_API_KEY }} \
              331355389718.dkr.ecr.eu-north-1.amazonaws.com/my-app:latest
