name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ sanjanasandaminifernando }}
        password: ${{ dckr_pat_ef32XYu57QmwSH6wqHI2ef_0GEA }}
        
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ sanjanasandaminifernando }}/forex-pipeline:latest
        
    - name: Deploy to server
      env:
        SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
      run: |
        echo "$SSH_KEY" > key.pem
        chmod 600 key.pem
        ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@$SERVER_IP \
          "docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/forex-pipeline:latest && \
           docker stop forex-app || true && \
           docker rm forex-app || true && \
           docker run -d --name forex-app -p 5000:5000 --restart always ${{ secrets.DOCKER_HUB_USERNAME }}/forex-pipeline:latest"
