name: Build, Push to AWS ECR & Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag & Push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: my-app
          IMAGE_TAG: latest
        run: |
          echo "Building Docker image..."
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          echo "Pushing Docker image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          debug: true
          script: |
            echo "=== SSH Connection Successful ==="
            echo "Current user: $(whoami)"
            echo "Working directory: $(pwd)"

            echo "=== Giving Docker permissions ==="
            sudo chmod 666 /var/run/docker.sock

            echo "=== Logging into ECR ==="
            aws ecr get-login-password --region eu-north-1 | sudo docker login --username AWS --password-stdin 331355389718.dkr.ecr.eu-north-1.amazonaws.com

            echo "=== Stopping and removing existing container ==="
            sudo docker stop my-app || true
            sudo docker rm my-app || true

            echo "=== Pulling latest image ==="
            sudo docker pull 331355389718.dkr.ecr.eu-north-1.amazonaws.com/my-app:latest

            echo "=== Running Docker container ==="
            sudo docker run -d --name my-app -p 5000:5000 \
              -e FASTFOREX_API_KEY=${{ secrets.FASTFOREX_API_KEY }} \
              331355389718.dkr.ecr.eu-north-1.amazonaws.com/my-app:latest

            echo "=== Waiting for app to be ready ==="
            sleep 10
            curl -f http://localhost:5000 || echo "App not responding yet"

